[package]
name = "rps-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec = { workspace = true, features = ["derive", "full"] }
scale-info = { workspace = true, features = ["derive"] }
gmeta.workspace = true
