[package]
name = "rps-io"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive", "full"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
gmeta = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
